.TH MANTA\-INIT 1 "2016" Manta "Manta Operator Commands"
.SH NAME
.PP
manta\-init \- initialize or update a Manta deployment
.SH SYNOPSIS
.PP
\fB\fCmanta\-init [OPTIONS] \-e|\-\-email EMAIL\fR
.SH DESCRIPTION
.PP
The \fB\fCmanta\-init\fR command is used during initial Manta deployment to download
Manta component images and configure the local Manta SAPI application.
.PP
\fB\fCmanta\-init\fR is also used when updating an existing Manta deployment to download
newer Manta component images.
.PP
Both of these use cases are described in the Manta Operator's Guide.  \fBDo not
run this command except as documented in the Manta Operator's Guide.\fP
.SH OPTIONS
.TP
\fB\fC\-c, \-\-concurrent_downloads N\fR
Specifies that no more than \fB\fCN\fR zone images should be downloaded
concurrently.
.TP
\fB\fC\-e, \-\-email EMAIL_ADDRESS\fR
Specifies that amon alarm notifications should be sent to \fB\fCEMAIL_ADDRESS\fR\&.
This option is required, even after the initial setup.
.TP
\fB\fC\-l, \-\-log_file FILE\fR
Specifies where the verbose activity log should be written.  The default path
is /var/log/manta\-init.log.  The special string "stdout" is used to dump to
stdout.
.TP
\fB\fC\-m, \-\-marlin_image IMAGE_UUID\fR
Use image \fB\fCIMAGE_UUID\fR for Marlin ("compute") zones.  This is not supported
and should only be used by Manta developers.
.TP
\fB\fC\-n, \-\-no_download\fR
Do not download any new zone images.
.TP
\fB\fC\-s, \-\-size SIZE\fR
Specifies that this Manta deployment as one of the predefined sizes "coal",
"lab", and "production".  The size controls parameters like the memory, CPU,
and disk resources assigned to deployed components.  "coal" is used for very
small deployments (e.g., a VM in a laptop).  "lab" is used for larger
single\-system deployments.  "production" is used for standard server
deployments.  Some additional constraints are imposed based on size, like the
fact that \fB\fCmanta\-factoryreset\fR will refuse to operate on "production"
deployments.
.SH EXAMPLES
.PP
See the Manta Operator's Guide.
.SH EXIT STATUS
.TP
\fB\fC0\fR
Success
.TP
Non\-zero
Generic failure.
.SH COPYRIGHT
.PP
Copyright (c) 2016 Joyent Inc.
.SH SEE ALSO
.PP
Manta Operator's Guide
