.TH MANTA\-DEPLOY\-DEV 1 "2016" Manta "Manta Operator Commands"
.SH NAME
.PP
manta\-deploy\-dev \- deploy Manta in a development environment
.PP
manta\-deploy\-lab \- deploy Manta on a lab machine
.PP
manta\-deploy\-coal \- deploy Manta in a laptop VM
.SH SYNOPSIS
.PP
\fB\fCmanta\-deploy\-dev [\-y] "lab" | "coal"\fR
.PP
\fB\fCmanta\-deploy\-lab [\-y]\fR
.PP
\fB\fCmanta\-deploy\-coal\fR
.SH DESCRIPTION
.PP
The \fB\fCmanta\-deploy\-dev\fR command automates much of the Manta setup process for a
single\-system Manta deployment.  You must select either a "lab" or "coal"
deployment.  This parameter determines how many metadata shards to create, how
many virtual nodes to create in the metadata tier, and how many of each kind of
component to deploy.
.PP
The \fB\fCmanta\-deploy\-lab\fR command is equivalent to \fB\fCmanta\-deploy\-dev lab\fR\&.
.PP
The \fB\fCmanta\-deploy\-coal\fR command is equivalent to \fB\fCmanta\-deploy\-dev \-y coal\fR\&.
.PP
See the Manta Operator's Guide for information on using these commands.
.SH OPTIONS
.TP
\fB\fC\-y\fR
Skips confirmations intended to improve reliability of the deployment process.
.SH EXIT STATUS
.TP
\fB\fC0\fR
Success
.TP
\fB\fC1\fR
Generic failure.
.TP
\fB\fC2\fR
The command\-line options were not valid.
.SH COPYRIGHT
.PP
Copyright (c) 2016 Joyent Inc.
.SH SEE ALSO
.PP
.BR manta-init (1), 
Manta Operator's Guide
